{
 "title": "Zamza.Server - general",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumer request duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(zamza_consumer_api_requests_duration_seconds_bucket[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(zamza_consumer_api_requests_duration_seconds_bucket[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "0.95q"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(zamza_consumer_api_requests_duration_seconds_bucket[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "0.5q"
    }
   ]
  },
  {
   "title": "Consumer request duration 0.95q  by operation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zamza_consumer_api_requests_duration_seconds_bucket[$__rate_interval])) by (le, method)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message queues size monitoring",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(round(zamza_background_tasks_leadership{task_name=\"MessageQueuesSize\"})) > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption status monitoring",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(round(zamza_background_tasks_leadership{task_name=\"PartitionConsumptionStatus\"})) > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 16, "x": 8, "y": 11 } },
  { "title": "Message queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Retry queue size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(zamza_retry_queue_size * on (instance) group_left clamp_max(clamp_min(round(zamza_background_tasks_leadership{task_name=\"MessageQueuesSize\"}), 0), 1))) or vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "max(zamza_retry_queue_size * on (instance) group_left clamp_max(clamp_min(round(zamza_background_tasks_leadership{task_name=\"MessageQueuesSize\"}), 0), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DLQ size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(zamza_dlq_size * on (instance) group_left clamp_max(clamp_min(round(zamza_background_tasks_leadership{task_name=\"MessageQueuesSize\"}), 0), 1))) or vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DLQ size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "max(zamza_dlq_size * on (instance) group_left clamp_max(clamp_min(round(zamza_background_tasks_leadership{task_name=\"MessageQueuesSize\"}), 0), 1))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}